### ISSUE TITLE
replace jshint + jscs by eslint

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#104]
Related to #101 with babel-eslint

**Comment by jonathanKingston** [comment]
I would be interested in helping pick this up to get me into the source unless you are stuck into it? (Just trying to find a way to cut in and help)

**Comment by MoOx** [comment]
This issue is somehow related to #101 

Here is the eslint file I am using 

```
---
# babel support more syntax stuff than eslint for now
parser: babel-eslint

ecmaFeatures:
  modules: true

env:
  es6: true
  browser: true
  node: true

# 0: off, 1: warning, 2: error
rules:
  # semicolons are useless
  semi: [2, "never"]

  quotes: [2, "double"]

  # 2 spaces indentation
  indent: [2, 2]

  # trailing coma are cool for diff
  comma-dangle: [2, "always-multiline"]

  # enforce comma at eol (never before)
  comma-style: [2, "last"]
```

You can take it if you want, cssnext is not that huge (only index.js < 200 lines + test/*)
