### ISSUE TITLE
--watch is not working on node 0.10/0.12

### ISSUE THREAD

**Issue by voronianski** [cssnext/cssnext#152]
Using cssnext version `1.6.0` but `--watch` option is not working.

```bash
cssnext --watch cssnext/index.css public/styles.css --verbose
```

**Comment by MoOx** [comment]
Please provide more info: node/npm version, os & command you are trying.

**Comment by voronianski** [comment]
@MoOx node `0.10.38`, npm `1.4.28`, OS X `10.10.3`, `cssnext --watch cssnext/index.css public/styles.css --verbose`

**Comment by MoOx** [comment]
Can you try --verbose as a first arg ?

**Comment by voronianski** [comment]
@MoOx tried `cssnext --verbose --watch cssnext/index.css public/styles.css` - no effect.

**Comment by MoOx** [comment]
What is you css input ?

**Comment by voronianski** [comment]
@MoOx 

```css
@import 'highlight.js/styles/github.css';
@import 'basscss';

header {
    position: fixed;
    display: block;
    top: 0;
    left: 0;
    right: 0;
    width: 100%;
    height: 32px;
    text-align: center;
    background-image: linear-gradient(45deg, rgba(255, 85, 0, 0.95), rgba(247, 95, 19, 0.8));
    border-bottom: 1px solid rgba(0,0,0,.1);
    box-shadow: 0 0 1px 1px rgba(0,0,0,0.1);
    z-index: 2;
}

.b2 {
    border-width: 2px;
}

:root {
    --font-family: 'Avenir Next', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    --container-width: 640px;
    --yellow: rgba(255, 220, 0, 0.45);
    --orange: #FC561E;
    --button-line-height: 1;
    --sb-progress-height: 8px;
    --button-big-padding-x: 1.25rem;
    --button-big-padding-y: 1.25rem;
}
```
