### ISSUE TITLE
Playground sometimes gets confused

### ISSUE THREAD

**Issue by topaxi** [cssnext/cssnext#165]
I'm not really sure when it happens, but sometimes the playground does weird things.

All I can say, I'm deleting the initial stuff and pasting in the new css.

Here side by side comparison:
![playground-bug](https://cloud.githubusercontent.com/assets/213788/8335228/b6a2502c-1a9c-11e5-83ff-a40bc63b4e91.png)

Tested in Firefox 41.0a1

**Comment by topaxi** [comment]
In the first tab I got this console warning: Warning: The selector ':--fizzbuzz' is undefined in CSS!

But even if I repaste the same snippet, it's compiled wrong and a new warning appears, works fine in a fresh tab though...

**Comment by MoOx** [comment]
It might be related to the plugin. Maybe a memory issue. This is weird.

**Comment by topaxi** [comment]
Yeah, maybe I shouldn't browse with nightlies...

I'll try to use a plain stable Firefox with a new profile for the playground for the next days and report if I can reproduce this.

**Comment by topaxi** [comment]
Okay I reproduced this now with the following code:

```css
@custom-selector :--foo .foo;

:--foo {
  color: bar;
}
```

After that, I **type** a new `@custom-selector`:

```css
@custom-selector :--foo .foo;
@custom-selector :--bar .bar;

:--foo {
  color: bar;
}
```

If I now use `:--bar` it will be "undefined" and the following happens:

Input:
```css
@custom-selector :--foo .foo;
@custom-selector :--bar .bar;

:--foo :--bar {
  color: bar;
}
```
Output:
```css
.foo {
  color: bar;
}
```

Tested in Firefox 38 and a completely new profile (no addons etc.)
