### ISSUE TITLE
Weird sassy code create a infinite loop

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#168]
The following code (which is not valid css) seems to create an infinite loop (even on the playground). This code can be parsed by postcss so I guess one plugin is having trouble with it.

Ref https://gitter.im/postcss/postcss?at=559107874a7048d725c22209

```css
/*  Variables - Sass Way */
$blue: blue;

:root {
    /* Variables - CSS Next */
    --red: red;
}

.userinfo {
	.username {
		color: var(--red);
	}

	.numrepos {
		color: $blue;
	}
}


@define-mixin icon $network, $color: blue {
    .icon.is-$(network) {
        color: $color;
        @mixin-content;
    }
    .icon.is-$(network):hover {
        color: white;
        background: $color;
    }
}

@mixin icon twitter {
    font-size: 10px;
}
@mixin icon youtube, red {
    font-size: 12px;
}
```

We should find wtf.
