### ISSUE TITLE
1.8.0 breaks embedded base64 data-uri

### ISSUE THREAD

**Issue by nickdima** [cssnext/cssnext#169]
It seems that `1.8.0` breaks embedded base64 data-uri. It happens for me with an icon font. The warning in the chrome console is: 'Failed to decode downloaded font'
Reverting back to `1.7.1` it works.

**Comment by ben-eb** [comment]
Are you using the `compress` option? Could you post a test case so that I could investigate?

**Comment by nickdima** [comment]
No, we don't use `compress`.
I can't really share the fontdata since it's private but I'll try with something public and get back. Meenwhile this is the syntax used:

``` css
@font-face {
	font-family: 'iconfont';
	src: url(data:application/x-font-ttf;charset=utf-8;base64,**DATA**) format('truetype'),
		 url(data:application/font-woff;charset=utf-8;base64,**DATA**) format('woff');
	font-weight: normal;
	font-style: normal;
}
```
