### ISSUE TITLE
Support :matches()

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#17]
```css
body :matches(h1, h2) {
  color: red;
}
```

should yields into

```css
body h1, body h2 {
  color: red;
}
```

poke @Eramdam
