### ISSUE TITLE
Custom Selectors sometimes generate REALLY unexpected output

### ISSUE THREAD

**Issue by awayken** [cssnext/cssnext#178]
I don't really know to explain this one except by example. It may be related to #177, which I just submitted, but it also might be unrelated.

Input:
```css
@custom-selector :--buttons button, input[type="button"];
@custom-selector :--hovers :hover, .hover;

:--buttons:--hovers {
    background: color(#ff9800 shade(20%));
}

button:--hovers,
input[type="button"]:--hover {
    background: color(#ff9800 shade(20%));
}
```

Output:
```css
:hover:--hovers,
.hover:--hovers {
    background: rgb(204, 122, 0);
}

:hover,
.hover
input[type="button"]:hover,

input[type="button"].hover {
    background: rgb(204, 122, 0);
}
```
