### ISSUE TITLE
Support for CSS @apply Rule - Error: no writecb in Transform class

### ISSUE THREAD

**Issue by JosefJezek** [cssnext/cssnext#213]
How to resolve this error? We need for Polymer Themes.

- http://tabatkins.github.io/specs/css-apply-rule/
- https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins
- https://github.com/StartPolymer/polymer-starter-kit-plus

I define mixin using `@apply` rule for `<paper-menu>` element.

```css
.navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
  };
}
```
 -> `Error: no writecb in Transform class`

Thank you
