### ISSUE TITLE
Client side polyfills

### ISSUE THREAD

**Issue by DylanPiercey** [cssnext/cssnext#221]
I understand that cssnext uses postcss and is purely preprocessing css at the moment. I think that this is extremely limiting. In my opinion we should take a tip from babel and ship with an (optional) runtime to enable some more killer features.

I'm thinking of stuff like this:

```css
/* Input */
.myclass {
    position: sticky;
    top: 10px;
    color: green;
}

/* Output */
.__sticky {
    /* Generic sticky styles if needed */
    position: fixed;
}

.myclass {
    color: green;
}
.__sticky.myclass {
/* Selector specific styles */
    top: 10px;
}
```

In this case the generated javascript would look something like this:

```javascript
// We could output our lists of selectors and some config that require js and generate a javascript polyfill during css compilation.

const CSS_NEXT = {
   "sticky": [
       {
             selector: ".myClass",
             options: {
                  top: 10px;
             }
       }
    ]
}; 

// And then we could have custom javascript handlers for any transform that needs it.
window.addEventListener("scroll", function () {
    CSS_NEXT.sticky.forEach(function (rule) {
        let matches = document.querySelectorAll(rule.selector);
        for (let el of matches) {
            if (window.pageYOffset > el.offsetTop + rule.options.top) {
                el.addClass(".__sticky");
            } else {
                el.removeClass(".__sticky");
            }
        }
    });
});
```

Now this example wouldn't be terribly efficient (although it could be much better). However I think that this is something that the css community as a whole should start exploring.

There are some libraries out there that attempt to manually parse the css at runtime and provide transforms but this is costly. I think there could be mostly performant polyfills for pretty much any new or custom css feature if we were to start leveraging both preprocessing and javascript.

This may be more something for postcss than here but what do you guys think?

**Comment by jedmao** [comment]
@DylanPiercey it seems like a lot of over engineering for something as simple as a mixin. Why not just use [`postcss-mixins`](https://github.com/postcss/postcss-mixins) and define the following mixin:

```css
@define-mixin sticky {
    position: fixed;
    /* Generic sticky styles if needed */
}
```

Or in JavaScript:

```js
require('postcss-mixins')({
    mixins: {
        sticky: function (mixin, dir) {
            return {
                position: 'fixed',
                /* Generic sticky styles if needed */
            };
        }
    }
});
```

Then, you can use it like so:

```css
.myclass {
    @mixin sticky;
    top: 10px;
    color: green;
}
```

Don't worry about the duplication, because gzip compression pretty much obliterates that!
