### ISSUE TITLE
Support for Repeating-radial/linear-gradient

### ISSUE THREAD

**Issue by eramdam** [cssnext/cssnext#59]
https://developer.mozilla.org/fr/docs/Web/CSS/repeating-radial-gradient
https://developer.mozilla.org/fr/docs/Web/CSS/repeating-linear-gradient

**Comment by MoOx** [comment]
Can you provide expected input & output? Not sure if we can transform this into classic `*-gradient()`s.

**Comment by eramdam** [comment]
Actually it would be only a matter of adding the corresponding vendor prefixes since it looks like it's supported on Chrome/Safari/Firefox with prefixes. 
So I'd say something like that
```css
body {
/* spec */
background: repeating-radial-gradient(black 2px, black 0px, white 5px, white 10px);
/* prefixed */
background: -moz-repeating-radial-gradient(black 2px, black 0px, white 5px, white 10px);
background: -webkit-repeating-radial-gradient(black 2px, black 0px, white 5px, white 10px);
background: -o-repeating-radial-gradient(black 2px, black 0px, white 5px, white 10px);

/* spec */
background: repeating-linear-gradient(black 2px, black 0px, white 5px, white 10px);
/* prefixed */
background: -moz-repeating-linear-gradient(black 2px, black 0px, white 5px, white 10px);
background: -webkit-repeating-linear-gradient(black 2px, black 0px, white 5px, white 10px);
background: -o-repeating-linear-gradient(black 2px, black 0px, white 5px, white 10px);
}
```
