### ISSUE TITLE
Wrong output of color() in cssnext playground

### ISSUE THREAD

**Issue by Macxim** [cssnext/cssnext#82]
In [cssnext playground](https://cssnext.github.io/cssnext-playground/), 
`color( [ <color> ] [red( | green( | blue( | alpha( | a(] ['+'] [<number>] ) )` doesn't seem to render properly.  
No problem with `['-'] ` though.

```css
.class{
  background-color: color(#2B88E6); /* expected: rgb(43, 136, 230) */
  color: color(#2B88E6 red(+30)); /* expected: rgb(73, 136, 230) */
  border-top-color: color(#2B88E6 green(+100)); /* expected: rgb(43, 236, 230) */
  border-bottom-color: color(#2B88E6 blue(+20)); /* expected: rgb(43, 136, 250) */
}
```
will render in
```css
.class{
  background-color: rgb(43, 136, 230); /* expected: rgb(43, 136, 230) */
  color: rgb(255, 136, 230); /* expected: rgb(73, 136, 230) */
  border-top-color: rgb(43, 255, 230); /* expected: rgb(43, 236, 230) */
  border-bottom-color: rgb(43, 136, 255); /* expected: rgb(43, 136, 250) */
}
```
I can't seem to reproduce this issue anywhere else.
