### ISSUE TITLE
Cannot use cssnext with postcss-cli

### ISSUE THREAD

**Issue by dfcreative** [cssnext/cssnext#98]
Hello. I see basic-case error on ubuntu, using cssnext as a postcss plugin.
postcss@4.1.5 is installed globally.
cssnext@1.3.0 is installed globally.

`index.css`:
```css
body {
	background: linear-gradient(red, gray);
}
```

Running 
`$ postcss -u cssnext index.css -o bundle.css`

returns

`[TypeError: object is not a function]`

Why?
